### ISSUE TITLE
Using ferma OGM with Gremlin Server

### ISSUE THREAD

**Issue by palandlom** [Syncleus/Ferma-benchmark#4]
Could you tell me - Is it possible to use FERMA over Gremlin Server (TinkerPop 3.2.6) with JanusGraphDB?

For now I use  gremlin client for sending queries to G-server in this way:

```
GryoMapper mapper = GryoMapper.build().addRegistry(JanusGraphIoRegistry.getInstance()).create();
MessageSerializer serializer = new GryoMessageSerializerV1d0(GryoMapper.build().addRegistry(JanusGraphIoRegistry.getInstance()));

/* Create gremlin cluster... */
Cluster cluster = Cluster.build("123.22.22.111").port(8182).serializer(serializer).create();
Client client = cluster.connect();
ResultSet res = client.submit("g.V().label()");
```

... therefore I have not idea about how could I get graph instance directly (like in the tutorial):

`FramedGraph fg = new DelegatingFramedGraph(graph, true, types);`

... to use traversal for getting instances of ferma-annotated classes.

**Comment by freemo** [comment]
@palandlom Hi Ferma absolutely works with janus grah, we have the JanusGraph developers themselves confirming that much, see here:

https://github.com/Syncleus/Ferma/pull/36

You would not go through Gremlin Server to do it though. You simply establish a connection to JanusGraph through tinkerpop as a Graph object then pass it to framed graph. At the link i showed you there is a project demonstrating it.

I also noticed you asked this question on stack exchange and switched your answer twice and closed your question here. Are you still having trouble or did you resolve this issue?

**Comment by palandlom** [comment]
For now we works with ferma and gremlin in parallel by using single Graph instance - in this way:
```
// ==== Base graph (JanusGraph) init========================//
// ========================================================//
CommonsConfiguration graphConfig = new CommonsConfiguration();
graphConfig.set("storage.backend", "berkeleyje");
graphConfig.set("storage.directory", "db/berkeley");
graphConfig.set("index.search.backend", "lucene");
graphConfig.set("index.search.directory", "db/lucene");
JanusGraph janusGraph = JanusGraphFactory.open(graphConfig);

// ==== GremlinServer init with Base graph ====================//
// ========================================================//
Settings settings = new Settings();
// ... setting could be changed
settings.graphs.clear();
GremlinServer gremlinServer = new GremlinServer(settings);
ServerGremlinExecutor executor = gremlinServer.getServerGremlinExecutor();
GraphManager graphManager = executor.getGraphManager();
// ... put base-graph into graph manager
graphManager.putGraph("graph", janusGraph);

// Define binding for using in queries:
// - "g" - graph traversal in
// - "graph" - graph instance
Bindings bindings = new SimpleBindings();
bindings.put("g", janusGraph.traversal());
bindings.put("graph", janusGraph);

// ==== FermaGraph with Base graph initialisation============//
// ==========================================================//
FramedGraph fg = new DelegatingFramedGraph<>(janusGraph, true, true);

// ======= Query execution by GS ============
// ==========================================
String qutr = "x = graph.addVertex('XXX');"
                + "y = graph.addVertex('ZZZ');"
                + "x.addEdge('----edge---->', y);" 
                + "graph.tx().commit();";

        CompletableFuture<Object> resultFuture = executor.getGremlinExecutor()
                .eval(qutr, bindings);

        Object result = resultFuture.get();

        if (result != null)
        {
            System.out.println(result.getClass());
            System.out.println(result.toString());
        }

// =====================================
gremlinServer.stop();
janusGraph.close();
```
 It will be interesting to see other solution from link you noted:
[https://github.com/evillasr/ferma-demo](https://github.com/evillasr/ferma-demo)
... but I have no accsess to it.

**Comment by freemo** [comment]
@palandlom you are creating the framed graph but then you dont use it, you go through the executor. Why?

**Comment by freemo** [comment]
@palandlom also you should have opened this ticket on the main ferma project, not here: https://github.com/Syncleus/Ferma

**Comment by palandlom** [comment]
It's just an example to show how we provide the additional way to interact with Graph instance through Gremlin-server.
Of course, it is possible to use this Graph instance by Ferma OGM by wrapping it by FramedGraph.

> also you should have opened this ticket on the main ferma project,

Okay, I'll keep that in mind. Thank you for your assistance.

**Comment by freemo** [comment]
@palandlom Ahh i see, so is there anything else I can help you with?
